Fix Python 2.7 CentOS issue by requiring argparse only in Py2.6
osiegmar/cloudwatch-mon-scripts-python pull request #19
Opened 2018-04-03 13:25 UTC by avengerpenguin

2018-04-12 20:12 UTC, lalkhum commented on setup.py
> + if sys.version_info == (2, 6):
Line 18 should rather be `sys.version_info[:2] == (2,7)`.

2018-05-09 05:39 UTC, lalkhum approved these changes

2020-12-19 10:42 UTC, osiegmar requested changes

2020-12-19 10:42 UTC, osiegmar commented on setup.py
> + if sys.version_info[:2] == (2, 6):
Sorry for my late response, I weren't notified via email for this PR.

I doubt this is enough as this is probably also required for Python < 2.7 **and** < 3.2.

2026-04-11 17:43 UTC, osiegmar commented
archiving this repository now

2026-04-11 17:43 UTC, closed without merging